version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Starting build..."
  build:
    commands:
      - echo "Build phase..."
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - index.html
    - '**/*'
  base-directory: '.'